- name: Download Gradle 4.10.2
  run: |
    wget -q https://services.gradle.org/distributions/gradle-4.10.2-bin.zip
    unzip -q gradle-4.10.2-bin.zip
    echo "$PWD/gradle-4.10.2/bin" >> $GITHUB_PATH

- name: Generate wrapper with Gradle 4.10.2
  run: gradle wrapper --gradle-version 4.10.2
